services:
  - type: web
    name: smart-village-complaint-management
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DB_TYPE
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: smart_village
      - key: DB_PORT
        value: "3306"
      - key: ADMIN_PASSWORD
        sync: false

